repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false

      - id: djlint
        name: lint html
        entry: make lint-html
        language: system
        types: [html]
        pass_filenames: false

      - id: pytest
        name: Run tests
        # Smart test execution: runs docker tests if container is up, otherwise falls back sqlite.
        # This ensures you can always commit code, even when Docker isn't running.
        entry: bash -c "docker compose ps web | grep -q 'Up' && make docker-test || DATABASE_URL= make test"
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: debug-statements
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
